<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DosenController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MataKuliahController;
use App\Http\Controllers\NilaiController;
use Illuminate\Support\Facades\Route;

// Redirect root to dashboard
Route::get('/', fn() => redirect()->route('dashboard'));

// All routes require authentication (Breeze middleware)
Route::middleware('auth')->group(function () {

    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // CRUD Resources
    Route::resource('kelas',        KelasController::class)->except(['show']);
    Route::resource('dosen',        DosenController::class)->except(['show']);
    Route::resource('mata-kuliah',  MataKuliahController::class);
    Route::resource('mahasiswa',    MahasiswaController::class);
    Route::resource('nilai',        NilaiController::class)->except(['show']);
});

// Auth routes (generated by Breeze)
require __DIR__.'/auth.php';